### ISSUE TITLE
Add windows machine to continuous integration framework

### ISSUE THREAD

**Issue by mdavezac** [DCPROGS/HJCFIT#69] opened 2015-11-09 18:18 UTC
Jenkins should be up to it now...
lf it were there, it would have  caught #63

**Comment by jenshnielsen** [comment] 2015-11-10 09:10
Hence why we created #64 which this is a duplicate of :wink:

**Closed by jenshnielsen** 2015-11-10 09:10 UTC

**Comment by mdavezac** [comment] 2015-11-10 13:52
Right... sorry I did try and find that ticket first...
